###############################################################################
#
# SDNet and V2EXPETH build instructions
#
# author: Henryk Richter <henryk.richter@gmx.net>
# 
# concept:
#  this makefile is intended mainly for cross compilation,
#  although building on AmigaOS works (see Common.mk)
#
# tools required:
#  - vbcc or m68k-amigaos-gcc (Default: gcc)
#  - vlink or GNU ld
#  - vasm (vasmm68k_mot)
#  - system headers (default: /opt/amigaos-68k/os-include, see Common.mk)
#
# porting:
#  see smakefile for native building using SAS/C
#
###############################################################################

###############################################################################
# Name, version
# 
###############################################################################
#DEVICEVERSION=1
#DEVICEREVISION=95
#DEVICEDATE=08.09.2018
#DEVICEEXTRA=Beta
ASMOBJECTS = $(SUBDIR)/vampuuid.o $(SUBDIR)/intervaltimer.o $(SUBDIR)/enc28j60.o $(SUBDIR)/enc28j60l.o
SUBDIR=sdnet

# two flavours of the same code base may be build with this setup
# leave DEVICEID2 empty to disable second build
DEVICEID=sdnet.device
DEFINES = # -DPROTO_V2EXPNET
ASMDEFS = # -DPROTO_V2EXPNET
CPU = 68020
TESTTOOL = sdnettest

DEVICEID2=v2expeth.device
DEFINES2 = -DPROTO_V2EXPNET
ASMDEFS2 = -DPROTO_V2EXPNET
CPU2 = 68020
TESTTOOL2 = v2expethtest

# additional housekeeping
EXTRACLEAN = $(SUBDIR)/sdnettest.o $(SUBDIR)/sdnettest.2o

###############################################################################
# import generic ruleset
# 
###############################################################################

include Common.mk

###############################################################################
# ruleset for test tools
#
###############################################################################

$(TESTTOOL) : $(ASMOBJECTS) $(SUBDIR)/sdnettest.o
	$(LINKEXE) $(LDFLAGS) -o $@ $(SUBDIR)/sdnettest.o $(ASMOBJECTS)

$(TESTTOOL2) : $(ASMOBJECTS) $(SUBDIR)/sdnettest.2o
	$(LINKEXE) $(LDFLAGS) -o $@ $(SUBDIR)/sdnettest.2o $(ASMOBJECTS)


